### ISSUE TITLE
Buying Power is incorrect for some users

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#1]
There seems to be a bug occurring for some users showing a higher buying power than what they have in their wallet. 

This seems to happen sometimes, and seems to be triggered by using the slider and/or inputting the order size manually. This is particularly weird because the `size` variable is not linked, afaik, to the `maxSize` variable which is represented as Buying Power in the UI.

`maxSize` is automatically calculated as a derived store from balance, leverage, current market, fee - here: https://github.com/capofficial/client/blob/main/src/lib/stores.js#L281

**Screen recording of bug**
https://cdn.discordapp.com/attachments/1043937411828293643/1049807481540460604/bug.mov

---

### Bounty
* This issue has a bounty of **$100**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by Ulydev** [comment]
I'm unable to reproduce - is there an address that can be impersonated to replicate the issue?

**Comment by kappacappa** [comment]
> I'm unable to reproduce - is there an address that can be impersonated to replicate the issue?

Same, cannot reproduce on my machine. But several users have reported seeing this bug in the private beta channel. It seems evasive and non consistent. Users that have reported this are on Brave / Chrome.

Attached some more screenshots below.

![Oxdark  cap io](https://user-images.githubusercontent.com/120023204/206193037-fe3e3efc-14c4-45e5-a3ba-cc1c0f431129.png)
![representative of how much margin you actually ha](https://user-images.githubusercontent.com/120023204/206193059-50be1d7b-065f-4b02-ab6d-3b94d0680405.png)

**Comment by 0xdarkcap** [comment]
https://github.com/capofficial/client/pull/43

**Comment by kappacappa** [comment]
Fixed in https://github.com/capofficial/client/pull/43
