### ISSUE TITLE
Order/position lines on chart overlayed by candles

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#12]
This is an issue that was fixed in v4.0.0 of TradingView's lightweight charts library as described here: https://github.com/tradingview/lightweight-charts/issues/1120

However, only v3.8 is publicly released and what CAP currently uses. We can potentially build their v4.0.0 from source to address this issue.

---

### Bounty
* This issue has a bounty of **$25**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by acaldas** [comment]
I can take this one. One alternative to porting the full library, which might have other side effects would be to just patch the code fix for this using [patch-package](https://www.npmjs.com/package/patch-package)

It seems this was the code fix: https://github.com/tradingview/lightweight-charts/commit/510b4d37f47db5790d27fe1d43b1a2b5d5230e19

**Comment by kappacappa** [comment]
@acaldas sounds good, assigned.
