### ISSUE TITLE
Allow option to input margin, not just size

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#15]
When placing a new order, allow users to set the margin they want to use in the input box, instead of size. This is useful for users who are used to explicitly setting the margin they want to use for their order.

A possible setup would be to have a small switch icon inside the Size input that switches between margin and size. Whatever the user selects should be saved to localStorage in the existing userSettings so that it persists on page reload.

When Margin is selected, the new order details (below the submit button) should show Size, and vice versa.

---

### Bounty
* This issue has a bounty of **$150**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by hjjinx** [comment]
Requesting to work on this.

**Comment by hjjinx** [comment]
#54
