### ISSUE TITLE
Add % corresponding to pool or CAP stake

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#18]
Users want to know how much of their LP or CAP stake represents, in percent of the total liquidity or staking pool. For example, if the user has 10 ETH in the pool and the pool's TVL is 200 ETH, we should show 5% somewhere. Same with CAP staking.

---

### Bounty
* This issue has a bounty of **$50**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by janbsw** [comment]
Hello, is this still open? If so, I'd like to complete this task.

**Comment by kappacappa** [comment]
@janbsw yes, this is available. You can go ahead and submit a fix.

**Comment by janbsw** [comment]
Created Pull request.

**Comment by kappacappa** [comment]
Solved in https://github.com/capofficial/client/pull/39
