### ISSUE TITLE
Fix P/L sorting

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#2]
Position P/L sorting is not working correctly. See screenshot below.

![setting you choose for PL one of the greens](https://user-images.githubusercontent.com/120023204/206190205-320327cc-d5f2-402d-9796-b30870bb5c94.png)

---

### Bounty
* This issue has a bounty of **$25**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by uncoolzero** [comment]
Uh, requesting to work on this
