### ISSUE TITLE
Display pool buffer amount

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#20]
In CAP v4, each liquidity pool has a buffer that holds trader losses and streams them into the main pool for collection by LPs. We should display how much is in the buffer for each pool.

---

### Bounty
* This issue has a bounty of **$25**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by fhrryDeveloper** [comment]
Request to work on this

**Comment by kappacappa** [comment]
@fhrryDeveloper assigned.

**Comment by fhrryDeveloper** [comment]
![image](https://user-images.githubusercontent.com/72539001/207825907-c17b3933-3835-4c82-8c22-9604eaa280b9.png)

I have a question. So will I sum all buffer values of each pool? And sum value will display on the top pool list?

**Comment by kappacappa** [comment]
@fhrryDeveloper no you probably just want to take the latest value for each pool.

**Comment by fhrryDeveloper** [comment]
Then where should I display this value?

**Comment by kappacappa** [comment]
@fhrryDeveloper in your image it is correct, but instead of summing the values under Latest Transactions, you simply take the most recent one.

**Comment by fhrryDeveloper** [comment]
Got it

**Comment by fhrryDeveloper** [comment]
Hi @kappacappa 
I finished this bounty. Please check it.
