### ISSUE TITLE
Display more information when staking/unstaking CAP

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#22]
* In the staking modal, show how much CAP a user has in their wallet. Click to stake them all.
* In the unstaking modal, allow the user to unstake all with one click.

---

### Bounty
* This issue has a bounty of **$50**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by adebayokehinde** [comment]
Requesting to work on this

**Comment by rebel117** [comment]
I'd like to work on this issue. I'll update the staking modal to show wallet CAP balance and add a one-click stake-all button, plus an unstake-all button in the unstaking modal.
