### ISSUE TITLE
Add CAP icon on staking page

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#25]
To be consistent with the asset icons displayed on the pool page.

---

### Bounty
* This issue has a bounty of **$20**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by rebel117** [comment]
I'd like to work on this issue. I'll add the CAP icon to the staking page to match the asset icons used on the pool page.
