### ISSUE TITLE
Fee percent not updating on market selection

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#3]
The fee % displayed when submitting new orders does not seem to update when switching markets. For example, some markets have 0.1% while another has 0.65% fee. Switching from one to the other does not update the fee percent displayed, unless the page is refreshed.

![Mong Loid Today](https://user-images.githubusercontent.com/120023204/206190814-10e01395-6329-45ca-9b7d-89474997872c.png)

---

### Bounty
* This issue has a bounty of **$25**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by MrKevin0308** [comment]
Hello @kappacappa 
I will work on this issue.

**Comment by kappacappa** [comment]
@MrKevin0308 thanks. You can submit a PR referencing this issue when you have the fix.

**Comment by MrKevin0308** [comment]
Hello @kappacappa 
I can't reproduce the issue...
Whenever I select the different pair, it's `SIZE` value has been initialized and fee is chaning without refresh

**Comment by kappacappa** [comment]
@MrKevin0308 looks like this has been fixed by https://github.com/capofficial/client/pull/42
Closing.
