### ISSUE TITLE
Commafy numbers based on locale

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#30]
Numbers greater than or equal to 1000 should be commafied, in some instances. For example, for en-US, 12345 would be:

12,345

For fr-FR, it would be 12 345.

Not all instances of numbers should be commafied. For example, it might not make sense to do this for prices. Perhaps it can be limited to amounts only.

---

### Bounty
* This issue has a bounty of **$50**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by fhrryDeveloper** [comment]
Hi Kappa. 
I'd like to fix this issue.

**Comment by fhrryDeveloper** [comment]
Hi Kappa.
So price and total money does not need to be commafied?
Only staking amount need to be commafied?

**Comment by kappacappa** [comment]
> Hi Kappa. So price and total money does not need to be commafied? Only staking amount need to be commafied?

We can try it for user asset, pool, staking balances for now @fhrryDeveloper

**Comment by fhrryDeveloper** [comment]
Hi @kappacappa 
I have finished this bounty and made PR.
Please check and give me feedback.

**Comment by fhrryDeveloper** [comment]
I updated it again. Please check
