### ISSUE TITLE
Reset New Order fields on market change

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#33]
- click on one market
- click on LIMIT
- put in a limit price
- click on another market
- limit price doesn't change

We should reset the new order fields when a user switches markets, to avoid confusion.

---

### Bounty
* This issue has a bounty of **$25**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by janbsw** [comment]
Completely reset it or just remove the limit/stop price?

**Comment by kappacappa** [comment]
@janbsw yes I believe resetting all fields, including size, limit, stop, tp, sl, and protected prices, would make sense.

**Comment by devtimnbr** [comment]
Could be done inside the setMarket function inside routing.js - would love to fix that if jan didn't already

**Comment by kappacappa** [comment]
@devtimnbr this issue is still unassigned as @janbsw already has an open issue/PR, so you can go ahead and submit a fix.

However I believe it would make sense to simply listen to $selectedMarket in NewOrder.svelte and clear the fields when it changes. That way the logic remains confined to the New Order panel.

**Comment by devtimnbr** [comment]
Thanks, makes sense! Will be fixed tonight
