### ISSUE TITLE
Display performance metrics for staking

### ISSUE THREAD

**Issue by luiscamposflores** [capofficial/client#34]
Add another table between "Your Pending Rewards" and "Latest Payments" with:
Title: "Total Pool Rewards"
Columns: ETH / USDC / WBTC / Total / Total per CAP (Total divided by the staked tokens)
Line 1 - last 1h
Line 2 - last 24h
Line 3 - last 7d
Line 4 - last 30d

**Comment by kappacappa** [comment]
This makes sense. Should probably be tracked in the chain indexer with a backend API providing CAP staking performance metrics.
