### ISSUE TITLE
Show wallet funds

### ISSUE THREAD

**Issue by luiscamposflores** [capofficial/client#35]
On staking, open position, pool deposit, always show wallet funds for the selected token.

**Comment by kappacappa** [comment]
This makes sense. For pool and staking, these are outlined in these issues:
* https://github.com/capofficial/client/issues/23
* https://github.com/capofficial/client/issues/22

For open position: what do you mean @luiscamposflores ?

**Comment by luiscamposflores** [comment]
You're absolutely right, I clearly need to sleep :) for open position (Submit Buy/Sell Order on the UI) it's the Buying and Selling power. Issue is duplicate and nothing more.
