### ISSUE TITLE
Scrollbar displaces chart

### ISSUE THREAD

**Issue by kappacappa** [capofficial/client#37]
A user on Chrome, Windows has reported this bug:

![image](https://user-images.githubusercontent.com/120023204/206431213-0fa41d50-12bf-41d3-bd4c-d42f50cfd7eb.png)

Where the chart is overlapping when the right scrollbar appears, probably on a small screen.

---

### Bounty
* This issue has a bounty of **$50**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by adebayokehinde** [comment]
I'm requesting to work on fixing this issue.

**Comment by kappacappa** [comment]
> I'm requesting to work on fixing this issue.

Sure, you can submit your fix.

**Comment by adebayokehinde** [comment]
PR made @kappacappa
