### ISSUE TITLE
Leverage slider unintuitive on 5x max leverage markets

### ISSUE THREAD

**Issue by janbsw** [capofficial/client#48]
![Leverage 1](https://user-images.githubusercontent.com/67024007/206723296-0cc83b5f-05ce-480d-be28-e1950736a53a.PNG)
![Leverage 2](https://user-images.githubusercontent.com/67024007/206723313-c8b2b354-6882-467a-b2f7-3c329e0f78c3.PNG)

The dots on the 5x leverage slider make it look like it should fix to them, the slider ends up in random spots between them, this just feels wrong when used.

**Comment by kappacappa** [comment]
@janbsw I agree. The dots are static at 25% intervals. We should adapt the slider dots to be more intuitive in case of max values like 5x leverage.

**Comment by janbsw** [comment]
@kappacappa It is also possible to set 0x leverage on 5x max markets, that shouldn't be possible, should it?

**Comment by kappacappa** [comment]
> @kappacappa It is also possible to set 0x leverage on 5x max markets, that shouldn't be possible, should it?

@janbsw You're right, that is a bug. Creating issue https://github.com/capofficial/client/issues/49

**Comment by janbsw** [comment]
Just removing the dots for maximum leverage  <=10   has yielded pretty good results

@kappacappa What do you think?

![LEv3](https://user-images.githubusercontent.com/67024007/206752037-5c0c5e57-a2c3-4eb7-a1d9-125fdd7c2bcd.PNG)
